### ISSUE TITLE
Multiple screenshot events on single screenshot

### ISSUE THREAD

**Issue by timothyerwin** [AzizAK/react-native-detector#15]
As mentioned in the header I am getting 3 screenshot calls when I take a single screenshot...

I checked that it only registers the listener once...any ideas?

```jsx
import {
  addScreenshotListener,
  removeScreenshotListener,
} from 'react-native-detector';

async componentDidMount() {
    this.screenshot = this.screenshot || addScreenshotListener(() => {
      console.log('screenshot');

      toast.show('screenshot');
    });

async componentWillUnmount() {
    removeScreenshotListener(this.screenshot);
}
```

**Comment by retyui** [comment]
the same problem (Android 11, react-native@0.65)

**Comment by retyui** [comment]
for my case  `ContentObserver::onChange(selfChange: Boolean, uri: Uri?, flags: Int)` was invoked with:

```log



uri: content://media/external/images/media/59645
flags: 4
path: /storage/emulated/0/DCIM/Screenshots/.pending-1631296636-Screenshot_20210903-205716_DetectScreenshot.jpg

uri: content://media/external/images/media/59645
flags: 8
path: /storage/emulated/0/DCIM/Screenshots/Screenshot_20210903-205716_DetectScreenshot.jpg


uri: content://media/external/images/media/59645
flags: 8
path: /storage/emulated/0/DCIM/Screenshots/Screenshot_20210903-205716_DetectScreenshot.jpg
```

**Comment by AzizAK** [comment]
@retyui I think this issue is fixed now right?

**Comment by retyui** [comment]
As foreground you can use a `throttle` @timothyerwin

**Comment by AzizAK** [comment]
the issue has been fixed, now the package saves the latest path and compare it with the upcoming one if it's not matching it will be considered as new screenshots, all the screenshots name with timestamp so it wont be duplicated

**Comment by JE-Zenarosa** [comment]
not working for me

import {
    addScreenshotListener,
    removeScreenshotListener,
  } from 'react-native-detector';

userDidScreenshot = () => {
        console.warn('lohin')
    };
   componentDidMount(){         
        
        addScreenshotListener(this.userDidScreenshot);
    }
