### ISSUE TITLE
How do we prevent the app from detecting screenshot when app is in background

### ISSUE THREAD

**Issue by ajitdas123** [AzizAK/react-native-detector#2]
How can we stop the package from detecting/recording screenshot events when the app goes in the background without using `appstate` of react-native to find the state. 

Also, 
I have stack navigation using `react-natvigation` with the `Home`,`Listing`  and  `Detail` page.  The package is used in the detail page. But if i take screenshot in the home page or listing page, its still detecting that. 

Here is my code for `Detail Page`

```

export default class Detail extends React.Component {
  screenCaptureListner;
  componentDidMount() {
     Platform.OS === 'ios' ? this.screenShot() : this.handleAndroidPermission();
  }
 
 componentWillUnmount() {
   removeScreenshotListener(this.screenCaptureListner);
 }

  handleAndroidPermission = async () => {
        try {
            const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                this.screenShot()
            }
        } catch (err) {
            console.warn(err);
        }
    };
    screenShot = () => {
        this.screenCaptureListner = addScreenshotListener(this.screenCaptured);
    }

 screenCaptured = () => {
  <!--- Here is some code --->
  }
}

**Comment by AzizAK** [comment]
Hello @ajitdas123, 
 
About your first question, the package does not unsubscribe by at self when app go to background you must implement it.

and for the second question react-navigation doesn't  unmount the screen while navigation read more here [react-navigation-life-cycle](https://reactnavigation.org/docs/navigation-lifecycle/)
