### ISSUE TITLE
Not logging

### ISSUE THREAD

**Issue by JodiRaina** [AzizAK/react-native-detector#5]
const Test = () => {
const requestPermission = async () => {
await PermissionsAndroid.request(
PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
{
title: 'Get Read External Storage Access',
message: 'get read external storage access for detecting screenshots',
buttonNeutral: 'Ask Me Later',
buttonNegative: 'Cancel',
buttonPositive: 'OK',
},
);
};

React.useEffect(() => {
requestPermission();
const userDidScreenshot = () => {
console.log('User took screenshot');
};
const listener = addScreenshotListener(userDidScreenshot);
return () => {
removeScreenshotListener(listener);
};
}, []);
return Test;
};
export default Test;

This is my code, but response system not logging can u help me?

**Comment by hysasuke** [comment]
Same here, got it working on IOS perfectly, but not working on Android

**Comment by Hasan-Metin-Emintek** [comment]
It was the same with me. Then, I inspected the example project and find that somehow it is imported differently from mine. So I advise you to check your MainApplication.java file and change your imported package name to `import com.reactnativedetector.DetectorPackage;` if it is different. I hope it helps you too.

**Comment by AzizAK** [comment]
Hello, Please can you check @Hasan-Metin-Emintek answer if its not working please let me know
