### ISSUE TITLE
Does this only work on device (not simulator?)

### ISSUE THREAD

**Issue by systemride** [AzizAK/react-native-detector#50]
Hitting the "Save Screen" button on the iOS simulator doesn't seem to trigger the screenshot event.

I am only able to get it to work on an actual device.

Is this the expected behavior?

Happy to submit a PR adding this to the README.

**Comment by Marquicas2** [comment]
On the simulator tabs, there's one called Device>Trigger Screenshot. That works as an screenshot on iOS :)

**Comment by systemride** [comment]
Yes, that worked thanks. 😃
